# Generated by Django 4.2.2 on 2023-06-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastel',
            name='big_pastel',
            field=models.IntegerField(default=0),
        ),
    ]
