# Generated by Django 4.2.2 on 2023-07-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pastel_big_pastel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastel',
            name='Rulon',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.rulon'),
            preserve_default=False,
        ),
    ]
