# Generated by Django 4.2.2 on 2023-07-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pastel_rulon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastel',
            old_name='Rulon',
            new_name='rulon',
        ),
    ]
