# Generated by Django 4.2.2 on 2023-07-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_rulon_pastel_rulon'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulon',
            name='information_pastel',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
