# Generated by Django 4.2.2 on 2023-07-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rulon_information_pastel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastel',
            name='xisob',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rulon',
            name='information_pastel',
            field=models.FileField(upload_to='D:\\REPO\\PastelBot'),
        ),
    ]
